repos:
    - repo: https://github.com/ambv/black
      rev: 21.10b0
      hooks:
          - id: black
            language_version: python3.8
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies: [flake8-docstrings]
    - repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
      rev: v2.1.1
      hooks:
          - id: pydocstyle
            exclude: migrations
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
          - id: isort

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.910-1"
      hooks:
          - id: mypy
            args: [--config-file=mypy.ini]
