"""Tabler."""

__title__ = "enigma"
__description__ = "Enigma emulator"
__url__ = ""
__version__ = "0.1"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
